default: &default

development:
  <<: *default
  http_triggers:
    self: http://localhost:3000/

test:
  <<: *default

production:
  <<: *default
  http_triggers:
    self: http://page.x-history.top/

